version: "3.9"

services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak
        volumes:
            - keycloak_db:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    keycloak:
        image: quay.io/keycloak/keycloak:24.0
        # НУЖНО именно start-dev, а не start
        command: start-dev --http-port 9080

        environment:
            # Здесь создаём админа автоматически
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin

            # Подключаем Postgres как хранилище
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://db:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak

            # При первом старте — импортируем наш realm
            KEYCLOAK_IMPORT: /opt/keycloak/data/import/smart-hcs.json

        # Монтируем JSON с realm
        volumes:
            - ./smart-hcs.json:/opt/keycloak/data/import/smart-hcs.json

        ports:
            - "9080:9080"
        depends_on:
            - db

volumes:
    keycloak_db:
